Repository Seagate/cortx-manager, pull requests merged in 2022-08, with the labels that each got.

#878 CORTX-33726: fix race condition on users quota check
  csm/core/agent/csm_agent.py
  csm/core/controllers/users.py
  csm/core/services/users.py
Labels: cla-signed

#879 CORTX-32719: Improve CSM service logs and error details
  csm/conf/setup.py
  csm/core/agent/api.py
  csm/core/agent/csm_agent.py
  csm/core/controllers/login.py
  csm/core/controllers/rgw/s3/users.py
  csm/core/controllers/users.py
  csm/core/services/rgw/s3/users.py
  csm/core/services/sessions.py
  csm/plugins/cortx/rgw.py
Labels: cla-signed

#880 CORTX-33835: Fix CSM mini-provisioning failure
  csm/conf/setup.py
  test/user_management/test_api_functional_requirements.py
Labels: cla-signed

#883 CORTX-33879: Fixed errors while fetching resource limit conf from consul confstore
  csm/conf/configure.py
  csm/conf/csm_default.conf
  csm/conf/etc/csm/csm.conf
  csm/conf/init.py
  csm/core/agent/api.py
  csm/core/blogic/const.py
Labels: cla-signed

#882 CORTX-33159: Codacy Fix
  csm/common/cluster.py
  csm/common/conf.py
  csm/common/fs_utils.py
  csm/common/timeseries.py
  csm/conf/configure.py
  csm/conf/csm_setup.py
  csm/conf/init.py
  csm/conf/post_install.py
  csm/conf/prepare.py
  csm/core/agent/api.py
  csm/core/agent/csm_agent.py
  csm/core/blogic/email_conf.py
  csm/core/controllers/users.py
  csm/core/data/models/session.py
  csm/core/providers/providers.py
  csm/core/services/permissions.py
  csm/core/services/sessions.py
  csm/core/services/stats.py
  csm/core/services/users.py
  test/service/test_csm_service.py
  test/user_management/test_api_functional_requirements.py
Labels: cla-signed, Status: Waiting to be Reviewed

#875 CORTX-32711:Implement REST API for query deployment
  csm/common/certificate.py
  csm/conf/etc/csm/csm.conf
  csm/core/agent/csm_agent.py
  csm/core/blogic/const.py
  csm/core/controllers/information.py
  csm/core/controllers/routes.py
  csm/core/controllers/storage_capacity.py
  csm/core/services/information.py
  csm/plugins/cortx/query_deployment.py
Labels: cla-signed, Status: Waiting to be Merged, Status: Changes Requested

#887 CORTX-33846: Integration with provisioner for query deployment
  csm/core/controllers/information.py
  csm/core/services/information.py
Labels: needs-attention, cla-signed

#888 CORTX-32262:CSM Connection handling
  csm/core/blogic/const.py
  csm/core/services/storage_capacity.py
  csm/plugins/cortx/rgw.py
Labels: cla-signed

#889 CORTX-32589: [Bug fix] Fixed mapping in capacity response
  schema/iam_operations_mapping.json
Labels: cla-signed

#892 CORTX-33949:CSM consul Connection handling
  csm/conf/setup.py
  csm/core/agent/csm_agent.py
  csm/core/blogic/const.py
  csm/core/services/session/session_factory.py
  csm/core/services/users.py
Labels: cla-signed

#894 CORTX-33950: GET IAM user capacity API with tenant as a path param
  csm/core/controllers/storage_capacity.py
Labels: cla-signed

#893 CORTX-34012: Query deployment modification with new design
  csm/cli/support_bundle/csm_bundle_generate.py
  csm/common/certificate.py
  csm/conf/csm_default.conf
  csm/conf/etc/csm/csm.conf
  csm/core/agent/csm_agent.py
  csm/core/blogic/const.py
  csm/core/controllers/information.py
  csm/core/controllers/routes.py
  csm/core/controllers/storage_capacity.py
  csm/core/services/information.py
  csm/core/services/query_deployment/topology_factory.py
Labels: cla-signed

#898 CORTX-33949:CSM consul Connection handling
  csm/common/utility.py
  csm/conf/configure.py
  csm/conf/init.py
  csm/conf/post_install.py
  csm/conf/prepare.py
  csm/conf/setup.py
  csm/conf/upgrade.py
  csm/core/agent/csm_agent.py
  csm/core/blogic/const.py
  csm/core/controllers/system_status.py
  csm/core/services/session/session_factory.py
  csm/core/services/system_status.py
  csm/core/services/users.py
Labels: cla-signed

#895 CORTX-30048: CSM Logs
  csm/core/agent/api.py
  csm/core/controllers/login.py
  csm/core/controllers/rgw/s3/users.py
  csm/core/controllers/storage_capacity.py
  csm/core/controllers/users.py
  csm/core/services/sessions.py
  csm/core/services/storage_capacity.py
Labels: cla-signed
